#!/usr/bin/env node

var fs = require('fs');
var Readable = require('stream').Readable;
var ncp = require('ncp').ncp;
var tmp = require('./_helpers').outDir;
var semver = require('../' + tmp + '/package.json').version;
var vdir = semver.substr(0, semver.lastIndexOf('.'));
var redirTpl = require('../lib/doc/redir.tpl');

fs.renameSync('./out', vdir);
fs.mkdirSync(vdir + '/docs/dist');
ncp('node_modules/bootstrap/fonts', vdir + '/fonts');
fs.createReadStream(tmp + '/ramda.js').pipe(fs.createWriteStream(vdir + '/docs/dist/ramda.js'));
fs.createReadStream('./lib/doc/main.js').pipe(fs.createWriteStream(vdir + '/docs/main.js'));
ncp(vdir + '/docs', 'docs');

function getTplStream(data) {
  var stream = new Readable({encoding: 'utf-8'});
  stream._read = function noop() {};
  stream.push(data);
  stream.push(null);
  return stream;
}

function fillTpl(tpl, path) {
  return tpl.replace(/{{redirTo}}/g, path);
}

getTplStream(fillTpl(redirTpl, vdir + '/index.html')).pipe(fs.createWriteStream('./index.html'));
